# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('artist', models.CharField(max_length=50, verbose_name='Artist')),
                ('url', models.URLField(verbose_name='Url')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('shots', models.CharField(default='', max_length=200, verbose_name='Shots')),
            ],
        ),
    ]
