# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170909_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50, verbose_name='Name')),
                ('location', models.CharField(max_length=50, verbose_name='Artist')),
                ('image', models.URLField(verbose_name='Url')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
    ]
